"""
Project: APEX AI Portfolio Management System
Course: Graduation Project / Engineering Project
Team Members:
- Saleem A. S. AbuZaid
- Rashad Naghdiyev
Advisor:
Prof.Dr. Selim Akyokuş
Description:
- Maintains Alembic database migration/configuration history for the APEX AI schema.
"""
"""add_news_id_to_events

Revision ID: 1f52ccdf69f3
Revises: 4e4d1741ebe3
Create Date: 2026-04-22 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f52ccdf69f3'
down_revision: Union[str, None] = '4e4d1741ebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'news', ['news_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('price_history_timestamp_idx')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('price_history_timestamp_idx', [sa.text('timestamp DESC')], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###
