"""
Project: APEX AI Portfolio Management System
Course: Graduation Project / Engineering Project
Team Members:
- Saleem A. S. AbuZaid
- Rashad Naghdiyev
Advisor:
Prof.Dr. Selim Akyokuş
Description:
- Maintains Alembic database migration/configuration history for the APEX AI schema.
"""
"""Sync schema with models

Revision ID: c9ab6908428e
Revises: 1f52ccdf69f3
Create Date: 2026-04-28 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ab6908428e'
down_revision: Union[str, None] = '1f52ccdf69f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recommendations Table
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ingest_ts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('process_ts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('signal_ts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('execution_price', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_recommendations_portfolio_id', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')

    # Execution Logs Table
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        # Rename side to action if it exists, or just add action
        # Note: In initial migration it was 'side'
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('signal_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('execution_ts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ingest_ts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('process_ts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('signal_ts', sa.Float(), nullable=True))
        # Drop 'side' if it exists
        # batch_op.drop_column('side') 

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_column('signal_ts')
        batch_op.drop_column('process_ts')
        batch_op.drop_column('ingest_ts')
        batch_op.drop_column('execution_ts')
        batch_op.drop_column('signal_id')
        batch_op.drop_column('action')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recommendations_portfolio_id', type_='foreignkey')
        batch_op.drop_column('execution_price')
        batch_op.drop_column('signal_ts')
        batch_op.drop_column('process_ts')
        batch_op.drop_column('ingest_ts')
        batch_op.drop_column('portfolio_id')
    # ### end Alembic commands ###
